---
name: Create GitHub release

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths: ['.github/workflows/**']

jobs:
  create-release:
    uses: obervinov/_templates/.github/workflows/release.yaml@main
