---
name: PR checks and tests

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
    paths:
      - '.github/workflows/**'

jobs:
  lint:
    uses: obervinov/_templates/.github/workflows/yamllint.yaml@main
  pr:
    uses: obervinov/_templates/.github/workflows/pr.yaml@main
