---
name: Create GitHub Release template

on: [workflow_call]  # yamllint disable-line rule:truthy

jobs:
  create-gh-release-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version in CHANGELOG.md
        run: echo "version=$(grep -E '## v[0-9]?([0-9]).[0-9]?([0-9]).[0-9]?([0-9])' CHANGELOG.md | head -1 | grep -Eo 'v[0-9]?([0-9]).[0-9]?([0-9]).[0-9]?([0-9])')" >> $GITHUB_OUTPUT
        id: changelogmdversion

      - name: Project name
        run: echo "project=$(echo ${GITHUB_REPOSITORY#obervinov/})" >> $GITHUB_OUTPUT
        id: project

      - name: Changes body
        run: sed -n '/## ${{ steps.changelogmdversion.outputs.version }} /,/## v/p' CHANGELOG.md | sed '$ d' > RELEASE_BODY.tmp
        id: changes

      - name: Create release
        uses: actions/create-release@v1.1.4
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.project.outputs.project }}:${{ steps.changelogmdversion.outputs.version }}
          tag_name: ${{ steps.changelogmdversion.outputs.version }}
          body_path: RELEASE_BODY.tmp
        env:
          GITHUB_TOKEN: ${{ github.token }}
