---
name: Plan and Apply Terraform

on: [workflow_call]  # yamllint disable-line rule:truthy

env:
  TF_CONTEXT: '.'
  TF_EXTRA_ARGS: ''
  AWS_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: ''
  AWS_SECRET_ACCESS_KEY: ''
  AWS_S3_ENDPOINT: ''

jobs:
  terraform-apply-template:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Terraform init
        run: |
          terraform init --upgrade

      - name: Terraform plan
        run: |
          cd "$TF_CONTEXT"
          terraform plan ${TF_EXTRA_ARGS} -compact-warnings -detailed-exitcode

      - name: Terraform apply
        run: |
          cd "$TF_CONTEXT"
          terraform apply ${TF_EXTRA_ARGS} -auto-approve -compact-warnings
