---
name: Plan and Apply Terraform

on: [workflow_call]  # yamllint disable-line rule:truthy

env:
  AWS_REGION: 'us-east-1'

jobs:
  terraform-fmt-template:
    runs-on: ubuntu-latest
    steps:
      - name: Set Context
        id: set-context
        run: echo "::set-output name=value::${{ inputs.TF_CONTEXT }}"

      - uses: actions/checkout@v3

      - name: Terraform fmt
        run: |
          cd "${{ needs.terraform-fmt-template.outputs.value }}"
          terraform fmt -recursive -check -diff

  terraform-docs-template:
    runs-on: ubuntu-latest
    steps:
      - name: Set Context
        id: set-context
        run: echo "::set-output name=value::${{ inputs.TF_CONTEXT }}"

      - uses: actions/checkout@v3

      - name: Terraform docs
        run: |
          cd "${{ needs.terraform-docs-template.outputs.value }}"
          terraform-docs markdown . > README.md

  terraform-apply-template:
    runs-on: ubuntu-latest
    steps:
      - name: Set Context
        id: set-context
        run: echo "::set-output name=value::${{ inputs.TF_CONTEXT }}"

      - uses: actions/checkout@v3

      - name: Terraform init
        run: |
          terraform init --upgrade

      - name: Terraform plan
        run: |
          cd "${{ needs.terraform-apply-template.outputs.value }}"
          terraform plan -compact-warnings -detailed-exitcode ${TF_EXTRA_ARGS}

      - name: Terraform apply
        run: |
          cd "${{ needs.terraform-apply-template.outputs.value }}"
          terraform apply -auto-approve -compact-warnings ${TF_EXTRA_ARGS}
