---
name: Build docker image template

on: [workflow_call]  # yamllint disable-line rule:truthy

jobs:
  build-docker-image-template:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: read
      contents: write
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine tag
        run: |
          # Determine tag from GITHUB_REF
          echo "TAG=$(if [ -z \"$GITHUB_REF_NAME\" ]; then echo ${GITHUB_REF#refs/tags/}; else echo ${GITHUB_REF_NAME//\//-}; fi)" >> $GITHUB_ENV

      - name: Build an image from Dockerfile
        run: |
          # Build image from Dockerfile
          docker build -t ghcr.io/${{ github.actor }}/${GITHUB_REPOSITORY#obervinov/}:$TAG --build-arg PROJECT_NAME=${GITHUB_REPOSITORY#obervinov/} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@d43c1f16c00cfd3978dde6c07f4bbcf9eb6993ca
        with:
          image-ref: "ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${TAG}"
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Push docker image to ghcr
        run: |
          # Push image to ghcr
          docker login --username ${{ github.actor }} --password ${{ github.token }} ghcr.io/${{ github.actor }}/${GITHUB_REPOSITORY#obervinov/}
          docker push ghcr.io/obervinov/${GITHUB_REPOSITORY#obervinov/}:$TAG
