---
name: Close milestone after release

on: [workflow_call] # yamllint disable-line rule:truthy

jobs:
  close-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Close milestone
        run: |
          # Get milstones
          milestones=$(curl -q -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository_owner}}/${{ github.event.repository.name }}/milestones)
          # Get the milestone for the current release
          current_version=$(echo ${{ github.ref }} | sed 's/refs\/heads\/.*\///')
          printf "Current version: %s\n" "$current_version"
          milestone=$(echo "$milestones" | jq -r ".[] | select(.title == \"$current_version\") | .number")
          printf "Found milestone with number: %s\n" "$milestone"
          # Close the milestone
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" -X PATCH -d "{\"state\": \"closed\"}" https://api.github.com/repos/${{ github.repository_owner}}/${{ github.event.repository.name }}/milestones/$milestone