---
name: Create and update Pull Request template

on: [workflow_call] # yamllint disable-line rule:truthy

jobs:
  create-update-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find PR for current branch
        id: find_pr
        run: |
          # Get all PRs
          PRs=$(curl -q -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository_owner}}/${{ github.event.repository.name }}/pulls)
          # Get the PR for the current branch
          current_branch=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          printf "Current branch: %s\n" "$current_branch"
          pr=$(echo "$PRs" | sed '/"body":/,/"created_at":/d'| jq -r ".[] | select(.head.ref == \"$current_branch\") | .number")
          printf "Found PR with number: %s\n" "$pr"
          echo "pr=$pr" >> $GITHUB_OUTPUT

      - name: PR does not exist
        id: check_pr
        run: |
            echo "::group::PR does not exist"
            echo "The PR does not exist for the current branch"
            echo "Please create a PR for the current branch"
            echo "::endgroup::"
            exit 1
        if: ${{ steps.find_pr.outputs.pr == null }}

      - name: Update PR body
        run: |
          # Get the PR body from the CHANGELOG.md file
          release_version=$(grep -E '## v[0-9]?([0-9]).[0-9]?([0-9]).[0-9]?([0-9])' CHANGELOG.md | head -1 | grep -Eo 'v[0-9]?([0-9]).[0-9]?([0-9]).[0-9]?([0-9])')
          printf "Release version: %s\n" "$release_version"
          release_body=$(sed -n "/## $release_version /,/## v/p" CHANGELOG.md | sed '$ d' | sed 's/\[.*\]//g' | sed 's/[(|)]//g' | perl -pe 's/\n/\\n/g')
          printf "Release body:\n%s\n" "$release_body"
          # Update the PR body
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" -X PATCH -d "{\"body\": \"${{ steps.changelog.outputs.pr_body }}\"}" https://api.github.com/repos/${{ github.repository_owner}}/${{ github.event.repository.name }}/pulls/${{ steps.find_pr.outputs.pr }}
        if: ${{ steps.find_pr.outputs.pr != null }}
