---
name: Verify README.md template

on: [workflow_call]  # yamllint disable-line rule:truthy

jobs:
  verify-readmemd-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract workflow version from README.md
        run: echo "version=$(awk -F '|' '/GitHub Actions Templates/ {print $3}' README.md | awk '{print $1}' | grep -Eo "v[0-9]+\.[0-9]+\.[0-9]+" | head -1)" >> $GITHUB_OUTPUT
        id: readme_version

      - name: Extract workflow versions from files in .github/workflows
        run: |
          workflow_versions=()
          for file in .github/workflows/*.yaml; do
            version=$(grep -oE '@v[0-9]+\.[0-9]+\.[0-9]+' "$file")
            workflow_versions+=("$version")
          done
          # Get the smallest version
          echo "version=$(printf "%s\n" "${workflow_versions[@]}" | sort -V | head -n 1)" >> $GITHUB_OUTPUT
        id: workflow_smallest_version

      - name: Compare versions between README.md and workflows
        run: |
            echo "::group::Compare versions"
            echo "README.md workflow version: ${{ steps.readme_version.outputs.version }}"
            echo "Smallest workflow version in GITHUB Actions: ${{ steps.workflow_smallest_version.outputs.version }}"
            echo "Please update the README.md file with the latest version of the workflow"
            echo "::endgroup::"
            exit 1
        if: ${{ steps.readme_version.outputs.version != steps.workflow_smallest_version.outputs.version}}

      - name: Result of the comparison between README.md and workflows
        run: echo "All workflows are up to date with the README.md file"
        if: ${{ steps.readme_version.outputs.version == steps.workflow_smallest_version.outputs.version}}
