name: Create new release

on: [workflow_call]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: version
      run: echo "::set-output name=version::$(grep "version =" pyproject.toml | awk '{printf $3}' | sed 's/"//g')"
      id: version
    - name:
      run: ls -lah
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
