name: Create new release

on: [workflow_call]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: ls
      run: ls -lah && pwd
    - name: Extract module version
      run: echo "::set-output name=version::$(grep "version =" pyproject.toml | awk '{printf $3}' | sed 's/"//g')"
      id: version
    - name: Extract branch name
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      id: branch
    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.branch.outputs.branch }}
        tag_name: test-actions
        #tag_name: ${{ steps.version.outputs.version }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
