---
name: Release template

on: [workflow_call]  # yamllint disable-line rule:truthy

jobs:
  release-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version in CHANGELOG.md
        run: echo "version=$(grep -E '## v[0-9]?([0-9]).[0-9]?([0-9]).[0-9]?([0-9])' CHANGELOG.md | head -1 | grep -Eo 'v[0-9]?([0-9]).[0-9]?([0-9]).[0-9]?([0-9])')" >> $GITHUB_OUTPUT
        id: changelogmdversion

      - name: Project name
        run: echo "project=$(echo ${GITHUB_REPOSITORY#obervinov/})" >> $GITHUB_OUTPUT
        id: project

      - name: Changes body
        run: sed -n '/## ${{ steps.changelogmdversion.outputs.version }} /,/## v/p' CHANGELOG.md | sed '$ d' > RELEASE_BODY.tmp
        id: changes

      - name: Create release
        uses: actions/create-release@v1.1.4
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.project.outputs.project }}:${{ steps.changelogmdversion.outputs.version }}
          tag_name: ${{ steps.changelogmdversion.outputs.version }}
          body_path: RELEASE_BODY.tmp
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Close milestone
        run: |
          # Get milstones
          milestones=$(curl -q -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository_owner}}/${{ github.event.repository.name }}/milestones)
          # Get the milestone for the current release
          current_version=$(echo ${{ github.ref }} | sed 's/refs\/heads\/.*\///')
          printf "Current version: %s\n" "$current_version"
          milestone=$(echo "$milestones" | jq -r ".[] | select(.title == \"$current_version\") | .number")
          printf "Found milestone with number: %s\n" "$milestone"
          # Check milestone percentage of completion
          milestone_completion=$(echo "$milestones" | jq -r ".[] | select(.number == \"$milestone\") | .closed_issues / .open_issues")
          printf "Milestone completion: %s\n" "$milestone_completion"
          if [ $milestone_completion -lt 1 ]; then
            echo "Milestone is not complete"
            exit 1
          fi
          # Close the milestone
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" -X PATCH -d "{\"state\": \"closed\"}" https://api.github.com/repos/${{ github.repository_owner}}/${{ github.event.repository.name }}/milestones/$milestone
