---
name: Plan and Apply Terraform

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      DOCS_DIRECTORIES:
        description: 'Comma-separated list of directories for terraform-docs'
        required: true
        type: string

jobs:
  terraform-fmt-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Terraform format code
        run: |
          terraform fmt -recursive

      - name: Check for Terraform formatting changes
        id: terraform-fmt-check
        run: |
          fmt_changes=$(git diff --name-only --exit-code || echo "changes")
          echo "::set-output name=fmt_changes::$fmt_changes"

      - name: Commit changes
        if: steps.terraform-fmt-check.outputs.fmt_changes == 'changes'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Apply Terraform formatting changes"
          git push

  terraform-docs-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Terraform docs
        run: |
          IFS=',' read -ra DIRS <<< "${{ github.event.inputs.DOCS_DIRECTORIES }}"
          for dir in "${DIRS[@]}"; do
            terraform-docs markdown "$dir" > "$dir/README.md"
          done
          