---
name: Plan and Apply Terraform

on:  # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  terraform-fmt-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Check cli
        run: |
          terraform --version

      - name: Terraform format code
        id: terraform-fmt-check
        run: |
          fmt_changes=$(terraform fmt -check -recursive)
          [ -n "$fmt_changes" ] && fmt_changes=true || fmt_changes=false
          echo "::set-output name=fmt_changes::$fmt_changes"
          terraform fmt -recursive

      - name: Commit changes
        if: steps.terraform-fmt-check.outputs.fmt_changes == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Apply Terraform formatting changes"
          git push

  terraform-docs-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Install Terraform docs
        run: |
          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          mv terraform-docs /usr/local/bin/terraform-docs
      
      - name: Check cli
        run: |
          terraform-docs --version
  
      - name: Terraform docs
        run: |
          if [ -f "terraform-docs.txt" ]; then
            while IFS= read -r dir; do
              /usr/local/bin/terraform-docs markdown "$dir" > "$dir/README.md"
              echo "::info::Updated $dir/README.md"
            done < "terraform-docs.txt"
          else
            echo "::warning::terraform-docs.txt not found. Skipping the task."
          fi
  
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add .
            git commit -m "Apply Terraform formatting changes"
            git push
          else
            echo "::set-output name=changes::false"
          fi
