---
name: Plan and Apply Terraform

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      DOCS_DIRECTORIES:
        description: 'Comma-separated list of directories for terraform-docs'
        required: true
        type: string

jobs:
  terraform-fmt-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set DOCS_DIRECTORIES
        run: echo "::set-output name=DOCS_DIRECTORIES::${{ github.event.inputs.DOCS_DIRECTORIES }}"

      - name: Terraform format code
        id: terraform-fmt-check
        run: |
          fmt_changes=$(terraform fmt -check -recursive)
          [ -n "$fmt_changes" ] && fmt_changes=true || fmt_changes=false
          echo "::set-output name=fmt_changes::$fmt_changes"
          terraform fmt -recursive

      - name: Commit changes
        if: steps.terraform-fmt-check.outputs.fmt_changes == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Apply Terraform formatting changes"
          git push

      - name: Upload DOCS_DIRECTORIES artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: DOCS_DIRECTORIES
          path: DOCS_DIRECTORIES.txt

  terraform-docs-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Terraform docs
        run: |
          echo  "${{ github.event.inputs.DOCS_DIRECTORIES }}"
          IFS=',' read -ra DIRS <<< "${{ github.event.inputs.DOCS_DIRECTORIES }}"
          for dir in "${DIRS[@]}"; do
            terraform-docs markdown "$dir" > "$dir/README.md"
          done

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Apply Terraform formatting changes"
          git push
