---
name: Plan and Apply Terraform

on:  # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  terraform-fmt-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Terraform format code
        id: terraform-fmt-check
        run: |
          fmt_changes=$(terraform fmt -check -recursive)
          [ -n "$fmt_changes" ] && fmt_changes=true || fmt_changes=false
          echo "::set-output name=fmt_changes::$fmt_changes"
          terraform fmt -recursive

      - name: Commit changes
        if: steps.terraform-fmt-check.outputs.fmt_changes == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Apply Terraform formatting changes"
          git push

  terraform-docs-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Terraform docs
        run: |
          if [ -f "terraform-docs.txt" ]; then
            while IFS= read -r dir; do
              terraform-docs markdown "$dir" > "$dir/README.md"
            done < "terraform-docs.txt"
          else
            echo "::warning::terraform-docs.txt not found. Skipping the task."
          fi
  
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add .
            git commit -m "Apply Terraform formatting changes"
            git push
          else
            echo "::set-output name=changes::false"
          fi
