---
name: Plan and Apply Terraform

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      TF_WORKSPACE:
        description: 'Terraform workspace directory'
        required: true
        type: string


jobs:
  terraform-fmt-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Terraform fmt
        run: |
          cd ${{ github.event.inputs.TF_WORKSPACE }}
          terraform fmt -recursive -check -diff

  terraform-docs-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Terraform docs
        run: |
          cd ${{ github.event.inputs.TF_WORKSPACE }}
          terraform-docs markdown . > README.md
