---
name: Plan and Apply Terraform

on: [workflow_call]  # yamllint disable-line rule:truthy

jobs:
  terraform-fmt-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Terraform fmt
        run: |
          cd $TF_WORKSPACE
          pwd
          echo $TF_WORKSPACE
          env
          terraform fmt -recursive -check -diff

  terraform-docs-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Terraform docs
        run: |
          cd $TF_WORKSPACE
          terraform-docs markdown . > README.md

  terraform-plan-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Terraform init
        run: |
          cd $TF_WORKSPACE
          terraform init --upgrade

      - name: Terraform plan
        run: |
          cd $TF_WORKSPACE
          terraform plan -compact-warnings -detailed-exitcode ${TF_EXTRA_ARGS}

  terraform-apply-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Terraform init
        run: |
          cd $TF_WORKSPACE
          terraform init --upgrade

      - name: Terraform apply
        run: |
          cd $TF_WORKSPACE
          terraform apply -auto-approve -compact-warnings ${TF_EXTRA_ARGS}
