---
name: Test Pylint template

on: [workflow_call]  # yamllint disable-line rule:truthy

jobs:
  test-pylint-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]


    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Analysing the code with PYLINT
        run: |
          pylint $(git ls-files '*.py')

      - name: Analysing the code with FLAKE8
        run: |
          flake8 . --count --show-source --statistics
