name: Compare package version template
 template

on: [workflow_call]

jobs:
  package-version-template:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check version in setup.py
      run: echo "version=v$(grep version='.*' setup.py | awk -F '=' '{print $2}'| sed "s/'//g" | sed 's/,//g')" >> $GITHUB_OUTPUT
      id: setuppy
    - name: Check version in pyproject.toml
      run: echo "version=v$(grep 'version = ".*"' pyproject.toml| awk '{print $3}' | sed 's/"//g')" >> $GITHUB_OUTPUT
      id: pyprojecttoml
    - name: Check version in CHANGELOG.md
      run: echo "version=$(grep -E "## v\d" CHANGELOG.md | head -1 | awk '{print $2}')" >> $GITHUB_OUTPUT
      id: changelogmdversion
    - name: Check date in CHANGELOG.md
      run: echo "date=$(grep -E "## v\d" CHANGELOG.md | head -1 | awk '{print $4}')" >> $GITHUB_OUTPUT
      id: changelogmddate
    - name: Check current date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      id: currentdate
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: tag
    - name: Old package version in setup.py
      run: |
          echo "::group::Compare versions"
          echo "The Git tag already matches the versions specified in setup.py"
          echo "Please check the version in those file and increase it according to your update"
          echo "::endgroup::"
          exit 1
      if: ${{ steps.setuppy.outputs.version == steps.tag.outputs.tag }}
    - name: Old package version in pyproject.toml
      run: |
          echo "::group::Compare versions"
          echo "The Git tag already matches the versions specified in pyproject.toml"
          echo "Please check the version in those file and increase it according to your update"
          echo "::endgroup::"
          exit 1
      if: ${{ steps.pyprojecttoml.outputs.version == steps.tag.outputs.tag }}
    - name: Old package version in changelog.md
      run: |
          echo "::group::Compare versions"
          echo "The Git tag already matches the versions specified in changelog.md"
          echo "Please check the version in those file and increase it according to your update"
          echo "::endgroup::"
          exit 1
      if: ${{ steps.changelogmdversion.outputs.version == steps.tag.outputs.tag }}
    - name: Old release date in changelog.md
      run: |
          echo "::group::Compare date"
          echo "The release version to create and the release version in the file CHANGELOG.md they differ"
          echo "Current: $(date +'%Y-%m-%d'), CHANGELOG.md: $(grep -E "## v\d" CHANGELOG.md | head -1 | awk '{print $4}')"
          echo "Please update the version CHANGELOG.md"
          echo "::endgroup::"
          exit 1
      if: ${{ steps.changelogmddate.outputs.date == steps.currentdate.outputs.dat }}
